# You can use this to import tunnels from your ~/.ssh/config file
import_hosts = ["dev1", "dev2"]
# or: (this is what happens if this config file can not be found)
import_all_hosts = true

[[tunnel]]
local_interface = "localhost" # This tunnel only accepts connections from your own computer
local_port = 8881
remote_host = "localhost"
remote_port = 8880
user = "my_username"
host = "dev1.example.com"
proxy_jump = "my_username@bastion.example.com"

[[tunnel]]
# Without "local_interface", this tunnel accepts connections on all interfaces
local_port = 8882
remote_host = "localhost"
remote_port = 8880
forwarded_port = 8888 # You can specify the port in the middle if you want, otherwise a random port is used
user = "my_username"
host = "dev2.example.com"
proxy_jump = "my_username@bastion.example.com"
