# You can use this to import tunnels from your ~/.ssh/config file
import_hosts = ["dev1", "dev2"]
# or: (this is what happens if this config file can not be found)
import_all_hosts = true

[[tunnel]]
user = "my_username"
host = "dev1.example.com"
proxy_jump = "my_username@bastion.example.com"
# Repeat the following section to forward multiple ports
[[tunnel.forward]]
local_interface = "localhost" # This tunnel only accepts connections from your own computer
local_port = 8881
remote_host = "localhost"
remote_port = 8880
[[tunnel.forward]]
local_interface = "localhost"
local_port = 8501
remote_host = "consul.service.consul"
remote_port = 8500

[[tunnel]]
user = "my_username"
host = "dev2.example.com"
proxy_jump = "my_username@bastion.example.com"
[tunnel.opts] # Additional options to net-ssh
port = 2222
keys = ["~/.ssh/my_key"]
[[tunnel.forward]]
# Without "local_interface", this tunnel accepts connections on all interfaces
local_port = 8882
remote_host = "localhost"
remote_port = 8880
